name: "Reminder creator"
on:
  issue_comment:
    types: [created]
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@v1.1.0
