permissions:
  pull-requests: none
  issues: write

name: "Stale issues"
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: ingakaspar/stale@2.0
        with:
          stale-issue-message: 'This issue is stale because it has been open for a week with no activity. Please, update the issue, or it will be closed.  There is no progress? &#8594; Specify the current state in a comment and put "status - on hold" label. This issue is a brainstorming space? &#8594; Convert it to a discussion by using the sidebar. </p>'
          close-issue-message: 'We have to close this issue because it has been stalled for 5 days with no activity. Check the section [update-your-issues](https://github.com/binari-construction) in our  Best Practices for more information on handling issues.</p>'
          days-before-stale: 7
          days-before-close: 5
          exempt-issue-labels: "status - on hold"
          stale-issue-label: "⚠️ stale"
          remove-stale-when-updated: true
